# Configuración común para todos los servicios
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:pass}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-user:eureka-pass@discovery-server:8761/eureka/
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    com.example: DEBUG
    org.springframework.cloud: INFO