# Configuración común para todos los servicios
spring:
  cloud:
    vault:
      uri: http://vault:8200
      token: myroot
      authentication: TOKEN
      kv:
        enabled: true
        backend: secret
      fail-fast: false
      connection-timeout: 5000
      read-timeout: 15000
      
eureka:
  client:
    service-url:
      defaultZone: http://eureka-user:eureka-pass@discovery-server:8761/eureka/
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    com.example: DEBUG
    org.springframework.cloud: INFO