server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mastererickdiaz/wrks-demo-config
          default-label: main
          search-paths: config
          timeout: 5
          clone-on-start: true

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
    org.springframework.cloud.commons.util: DEBUG