server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mastererickdiaz/wrks-demo-config
          default-label: main
          search-paths: config
          timeout: 30
          clone-on-start: true
          force-pull: true

server:
  connection-timeout: 30000
  servlet:
    session:
      timeout: 30m

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config.server: INFO