server:
  port: 8888

spring:
  application:
    name: config-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,refresh
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
      
spring:
  cloud:
    config:
      server:
        git:
          timeout: 10
          clone-on-start: true
