server:
  port: 8761

spring:
  application:
    name: discovery-server
  security:
    user:
      name: eureka-user
      password: eureka-pass

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always